---
- name: Create service account for Spark Jobserver
  user: name={{ spark_user }}
  tags: ["spark-jobserver-user"]

- name: Ensure Spark Jobserver log and run directories exist
  file: path="{{ item }}"
        owner={{ spark_user }}
        group={{ spark_user }}
        mode=0755
        state=directory
  with_items:
    - "{{ spark_jobserver_log_dir }}"
    - "{{ spark_jobserver_run_dir }}"

- name: Download Spark Jobserver distribution
  get_url: url="{{ spark_jobserver_mirror }}/spark-jobserver-{{ spark_jobserver_version }}.tar.gz"
           dest="{{ spark_jobserver_src_dir }}/spark-jobserver-{{ spark_jobserver_version }}.tgz"

- name: Extract Spark Jobserver distribution
  unarchive: src="{{ spark_jobserver_src_dir }}/spark-jobserver-{{ spark_jobserver_version }}.tar.gz"
             dest="{{ spark_jobserver_usr_parent_dir }}"
             copy=no
             creates="{{ spark_jobserver_usr_parent_dir }}/spark-jobserver-{{ spark_jobserver_version }}"

- name: Setup Spark Jobserver distribution symlinks
  file: src="{{ item.src }}"
        dest="{{ item.dest }}"
        state=link
  with_items:
    - { src: "{{ spark_jobserver_usr_parent_dir }}/spark-jobserver-{{ spark_jobserver_version }}", dest: "{{ spark_jobserver_lib_dir }}" }
  tags: ["symlinks"]

- name: Configure Spark Jobserver environment
  template: src={{ item }}
            dest="{{ spark_jobserver_lib_dir }}/{{ item }}"
            mode=0755
  with_items:
    - local.conf
    - settings.sh
    - shiro.ini
  tags: ["config"]
