---
- name: Create service account for Spark Zeppelin
  user: name={{ spark_user }}
  tags: ["spark-jobserver-user"]

- name: Ensure Spark Zeppelin log and run directories exist
  file: path="{{ item }}"
        owner={{ spark_user }}
        group={{ spark_user }}
        mode=0755
        state=directory
  with_items:
    - "{{ spark_zeppelin_log_dir }}"
    - "{{ spark_zeppelin_run_dir }}"

- name: Download Spark Zeppelin distribution
  get_url: url="{{ spark_zeppelin_mirror }}/zeppelin-{{ spark_zeppelin_version }}/zeppelin-{{ spark_zeppelin_version }}-bin-all.tgz"
           dest="{{ spark_zeppelin_src_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all.tgz"

- name: Extract Spark Zeppelin distribution
  unarchive: src="{{ spark_zeppelin_src_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all.tgz"
             dest="{{ spark_zeppelin_usr_parent_dir }}"
             copy=no
             creates="{{ spark_zeppelin_usr_parent_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all"

- name: Setup Spark Zeppelin distribution symlinks
  file: src="{{ item.src }}"
        dest="{{ item.dest }}"
        state=link
  with_items:
    - { src: "{{ spark_zeppelin_usr_parent_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all", dest: "{{ spark_zeppelin_lib_dir }}" }
    - { src: "{{ spark_zeppelin_usr_parent_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all/conf", dest: "{{ spark_zeppelin_conf_dir }}" }
  tags: ["symlinks"]

- name: Configure Spark Zeppelin environment
  template: src={{ item }}
            dest="{{ spark_zeppelin_usr_parent_dir }}/zeppelin-{{ spark_zeppelin_version }}-bin-all/conf/{{ item }}"
            mode=0755
  with_items:
    - zeppelin-env.sh
    - zeppelin-site.xml
    - shiro.ini
  tags: ["config"]

- name: Add Spark Zeppelin service script
  template: src=upstart.conf
            dest=/etc/init/zeppelin.conf
            mode=0755
  tags: ["service"]
