{{ rails_environment }}:
    
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default: &default_client
      database: {{ mongodb_database_connec }}
      hosts:
        - {{ mongo.cluster.dns.master }}:27017
        - {{ mongo.cluster.dns.replica1 }}:27017
        - {{ mongo.cluster.dns.replica2 }}:27017
      options: &default_client_options
        user: {{ mongodb_user_connec }}
        password: {{ mongodb_password_connec }}
        auth_source: {{ mongodb_database_connec }}
        max_pool_size: 1000
        min_pool_size: 5
    
    secondary:
      <<: *default_client
      options:
        <<: *default_client_options
        read:
          mode: :secondary_preferred


  # Configure Mongoid specific options. (optional)
  options:
    preload_models: true
    raise_not_found_error: false
